default:
  image: rust:latest

stages:
  - build
  - test
  - documentation

building workspace:
  stage: build
  script:
    - "cargo build --workspace"

testing workspace:
  stage: test
  script:
    - "cargo test --workspace"

pages:
  stage: documentation
  image: rustlang/rust:nightly
  script:
    - "mkdir .public"
    - "mkdir build-docs"
    - "cargo doc +nightly --no-deps --target-dir build-docs"
    - "cp -r build-docs/doc/* .public/"
    - "mv .public public"
  artifacts:
    paths:
      - public
  only:
    - master

