default:
  image: rust:latest

stages:
  - build
  - test

building workspace:
  stage: build
  script:
    - "cargo build --workspace"

testing workspace:
  stage: test
  script:
    - "cargo test --workspace"
