[package]
name = "khalas"
version = "0.1.0"
authors = ["Muhannad Alrusayni <Muhannad.Alrusayni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = { git = "https://github.com/David-OConnor/seed" }
web-sys = "^0.3"
palette = "0.4.1"
derive_more = { git = "https://github.com/JelteF/derive_more" }
derive_rich = { git = "https://gitlab.com/muhannad_alrusayni/derive_rich" }

[workspace]
members = [
    "examples/testing",
    "examples/server"
]
