[workspace]
members = [
  # crates
  "core",
  "html",
  "elements",
  # helper crates
  "cli",
  "derive",
  # examples
  "examples/simple_counter",
  "examples/full_counter",
  "examples/all_elements",
]
