[package]
name = "khalas"
version = "0.1.0"
authors = ["Muhannad Alrusayni <Muhannad.Alrusayni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = { git = "https://github.com/David-OConnor/seed" }
palette = "0.4.1"
derive_more = { git = "https://github.com/JelteF/derive_more" }
derive_rich = { git = "https://gitlab.com/muhannad_alrusayni/derive_rich" }
wasm-bindgen = "0.2.58"
indexmap = "1.3.2"

[dependencies.web-sys]
version = "^0.3.35"
features = [
    "WheelEvent", "CompositionEvent", "HtmlInputElement", "InputEvent",
    "FocusEvent", "DragEvent", "DomRect", "Element"
]

[workspace]
members = [
    "examples/testing",
    "examples/counter",
    "examples/server"
]
