[workspace]
members = [
  # crates
  "core",
  "html",
  "elements",
  # helper crates
  "cli",
  "derive",
  # examples
  "elements/examples/counter",
  "elements/examples/full_counter",
  "elements/examples/all_elements",
]
